name: ASP.NET CI
on : [push]
jobs:
  build:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@master

    - name: Setup NuGet.exe
      uses: nuget/setup-nuget@v1

    - name: restoring nuget
      working-directory: win32
      run: nuget restore
  
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1
  
    - uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x86
  
    - name: MSBuild
      working-directory: win32
      run: msbuild
